### ISSUE TITLE
Release a version which doesn't require Doctrine

### ISSUE THREAD

**Issue by alexanderdean** [snowplow-archive/codeigniter-paypal-ipn#1]
If you want this, vote this issue up so I know this is important

**Comment by jmagnone** [comment]
It would be great if you can avoid the dependency w/Doctrine. (I Vote Up)

**Comment by chchrist** [comment]
+1

**Comment by hasitha** [comment]
I'd also like to vote for a Doctrine free version. Simple active record implementation would allow us to then convert it to another ORM of our choice.

**Comment by th30ne** [comment]
+1

**Comment by mcsmix** [comment]
+1

**Comment by PadraigK** [comment]
+1

**Comment by seinoxygen** [comment]
+1

**Comment by nolochemical** [comment]
+1 Thanks for the great library.

**Comment by jurajivan** [comment]
+1 for sure

**Comment by dspangenberg** [comment]
+1

**Comment by haganbt** [comment]
+1 please ;)

**Comment by bigmike7801** [comment]
+2

**Comment by zbrox** [comment]
+1

**Comment by alexanderdean** [comment]
Okay I have uploaded an ActiveRecord version. I'm using it on a site with txn_type web_accept - let me know how you get on with it.
