### ISSUE TITLE
Where it generates paypal button or form ?

### ISSUE THREAD

**Issue by savsoft** [snowplow-archive/codeigniter-paypal-ipn#13]
Hi,

I have some confusion that is it also generate paypal buy now button or form?
if yes, then how it get the ipn value (return url) and other field like item name, amount etc ?

Thanks,
B. Singh

**Comment by alexanderdean** [comment]
Hi, no this library doesn't generate PayPal buttons or forms:

> This library focuses on the “post-payment” workflow, i.e. the processing required once
> the payment has been made and PayPal has posted an Instant Payment Notification call to
> the IPN listener (aka your CodeIgniter IPN controller).
> All pre-payment functionality (e.g. posting the checkout information to PayPal) and custom
> post-payment workflow (e.g. sending emails) is left as an exercise to the reader.

Closing this ticket as I have no plan to add this functionality.
