### ISSUE TITLE
Stumped

### ISSUE THREAD

**Issue by mdvm73** [snowplow-archive/codeigniter-paypal-ipn#16]
I have set this up on several CI 2 installs and cannot get any of them to work. The current install is with CI 2.1 and is using spark php-activeRecord 2.0.2 model. I am a newbie to CI, but had at one point gotten this to work, I don't remember what i did, but now it won't even work with a fresh install and only running the ipn without any tweeks, and no activerecord.

**Comment by alexanderdean** [comment]
Hi **mdvm73** - if there are issues running codeigniter-paypal-ipn in CI 2, do please let us know what they are!

Regarding php-activeRecord: there are currently two versions of codeigniter-paypal-ipn: one using CodeIgniter’s modified version of the Active Record Database Pattern, and one using Doctrine (tested with 1.2.3). We don't have a version yet that works with spark php-activeRecord 2.0.2 - if you would like to contribute one, that would be awesome!

**Comment by mdvm73** [comment]
i can't figure it out, but nothing else works either. handwritten w/ no framework, ipn generators, followed several tutorials for fsocket and curl, nothing seems to work and I can't for the life of me figure out why. ipn gets sent and green lights across the board, but nothing logs and nothing saves to data base, and the closest i get to a error message is when thepaypal tech generated code isn't set to sand box I actually get an invalid email :P does being on a shared server have something to do with it? I'm lost but it's not with only your library, it worked at one point in the past... still stumped.

**Comment by alexanderdean** [comment]
Have you tried the debug mode? See:

https://github.com/orderly/codeigniter-paypal-ipn/issues/9#issuecomment-3565096

for details.

**Comment by mdvm73** [comment]
it gave me an error that says something like no IPN::load function which is what made me think it might be CI 2 is not compatable, is there a version you know that works for sure with the plugin thank you for the immediate response btw

**Comment by alexanderdean** [comment]
That sounds like it _might_ be a CI 2 issue... The library should work with the final release of CI 1.x:

http://downloads.codeigniter.com/CodeIgniter_1.7.3.zip

**Comment by mdvm73** [comment]
thank you I will give it a go

**Comment by alexanderdean** [comment]
Let me know how you get on... If the library is not CI 2 compatible then that's something we need to look into... Will leave this ticket open

**Comment by mdvm73** [comment]
totally something I'm doing I'm new to ci and have scratched by barely i must not be setting something up, Fatal error: Call to a member function library() on a non-object in /home/tadiup/public_html/inPPipn/system/application/controllers/ipn.php on line 29

**Comment by mdvm73** [comment]
i've narrowed it down quite a bit, i can get invalid all day long, but nothing happens when all signs point to validated either the message is not getting sent, or the ipn sand box is dropping variables which breaks the code. which u pointed out earlier. I hope

**Comment by mdvm73** [comment]
live button returns same error, are there any config or auto load variables(besides the seller email) i could be missing, or could it be something todo with using a shared server?

**Comment by mdvm73** [comment]
A PHP Error was encountered

Severity: Notice

Message: Undefined property: Ipn::$load

Filename: controllers/ipn.php

Line Number: 29

Fatal error: Call to a member function library() on a non-object in *.com/application/controllers/ipn.php on line 29

**Comment by alexanderdean** [comment]
You have a problem with your installation I think - see eg http://stackoverflow.com/questions/8322124/codeigniter-call-to-a-member-function-select-on-a-non-object

Have you definitely installed the file active record/libraries/PayPay_IPN into your libraries folder?

**Comment by mdvm73** [comment]
yes, I'll check out this link. it happens with both codeigniter 1.7 and CI2. on the CI2 install i had to add 'CI_' to the extends controller class in the ipn controller, but like i said, i'm getting the error in both installs.

**Comment by alexanderdean** [comment]
I'd try getting an example controller working first, and then a controller which loads a simple library (not PayPal_IPN)...

**Comment by mdvm73** [comment]
controller loaded library and displayed a string from the library. do i have to have a ssl certificate, or something that would be considered a no brainer for paypal integration?

**Comment by mdvm73** [comment]
It was something very stupid i think, out ipn was the name of the class for the controller, out of desperation i added pp_. so aparently, a class should have more than 3 letters in it? Learned that the uber-ultra-3 days wasted way. holy mama thank you so much for your patience I'll close this ticket, and you can erase it :P

**Comment by alexanderdean** [comment]
Maybe it was a name clash between your controller and the library?!
On Jul 13, 2012 8:51 AM, "mdvm73" <
reply@reply.github.com>
wrote:

**Comment by mdvm73** [comment]
funny how code can make you feel brilliant one second and a moron the next have a great evening

**Comment by alexanderdean** [comment]
True!
