### ISSUE TITLE
Duplicate rows in database

### ISSUE THREAD

**Issue by jpbringhurst** [snowplow-archive/codeigniter-paypal-ipn#18]
After setting up, when I run a test order I get a successful order logged in the db and then right after I get another record of failed in the db. Any idea why this is happening?

**Comment by alexanderdean** [comment]
Weird... It's worth going through the debug steps if you haven't already:

https://github.com/orderly/codeigniter-paypal-ipn/issues/9

**Comment by jpbringhurst** [comment]
Thanks for the quick response. Do I have to be using the sandbox mode for the debug to work? Currently I am running tests live.

Date: Tue, 4 Dec 2012 16:07:29 -0800

**Comment by alexanderdean** [comment]
Debug mode should work with live... I'd always recommend getting the library working with the sandbox first, then migrating live...

**Comment by jpbringhurst** [comment]
I followed the instructions but I don't get any error on screen (there is a no post data error in the log). I have it redirecting to a dashboard if there is not a valid IPN. It acts like it is calling the ipn code twice so the first one comes through with valid data but the second one doesn't.

Date: Tue, 4 Dec 2012 16:15:43 -0800

**Comment by jpbringhurst** [comment]
Could it be due to the configuration in my paypal account? I have IPN notifications on as well as auto return and PDT enabled. Both have the same url for return and messages.

Date: Tue, 4 Dec 2012 16:15:43 -0800

**Comment by alexanderdean** [comment]
That sounds like the problem - two different things pinging your IPN
handler. Your IPN handler should only be pinged with IPN confirmation
messages - use a different controller for anything else...

A

**Comment by jpbringhurst** [comment]
Great - I will try disabling the PDT portion of it.

Thank you for your help.

Date: Tue, 4 Dec 2012 16:48:18 -0800

**Comment by alexanderdean** [comment]
Great, closing
